In [2]:
import pandas as pd

In [3]:
data = pd.read_csv("C:/Users/shaik/OneDrive/Desktop/Data science26/DataSetsbyKaggle/dataset_prac/cleaned_sales_data.csv")

In [4]:
data

,TransactionNo,Date,ProductNo,ProductName,Price,Quantity,CustomerNo,Country,ReturnFlag
0,581482.0,09/12/2019,22485,Set Of 2 Wooden Market Crates,21.47,12.0,17490.0,United Kingdom,False
1,581475.0,09/12/2019,22596,Christmas Star Wish List Chalkboard,10.65,36.0,13069.0,United Kingdom,False
2,581475.0,09/12/2019,23235,Storage Tin Vintage Leaf,11.53,12.0,13069.0,United Kingdom,False
3,581475.0,09/12/2019,23272,Tree T-Light Holder Willie Winkie,10.65,12.0,13069.0,United Kingdom,False
4,581475.0,09/12/2019,23239,Set Of 4 Knick Knack Tins Poppies,11.94,6.0,13069.0,United Kingdom,False
...,...,...,...,...,...,...,...,...,...
431703,545333.0,01/03/2019,22727,Alarm Clock Bakelike Red,17.90,1.0,17333.0,United Kingdom,False
431704,545333.0,01/03/2019,22745,Poppy's Playhouse Bedroom,14.48,2.0,17333.0,United Kingdom,False
431705,545333.0,01/03/2019,22746,Poppy's Playhouse Livingroom,14.48,2.0,17333.0,United Kingdom,False
431706,545333.0,01/03/2019,22747,Poppy's Playhouse Bathroom,14.48,2.0,17333.0,United Kingdom,False
431707,545333.0,01/03/2019,22748,Poppy's Playhouse Kitchen,14.48,2.0,17333.0,United Kingdom,False

In [5]:
data.shape

(431708, 9)

In [6]:
data.isnull().sum()

TransactionNo    6816
Date                0
ProductNo           0
ProductName         0
Price               0
Quantity            0
CustomerNo         44
Country             0
ReturnFlag          0
dtype: int64

In [7]:
data["TransactionNo"]

0         581482.0
1         581475.0
2         581475.0
3         581475.0
4         581475.0
            ...
431703    545333.0
431704    545333.0
431705    545333.0
431706    545333.0
431707    545333.0
Name: TransactionNo, Length: 431708, dtype: float64

In [8]:
data["CustomerNo"].unique()

array([17490., 13069., 12433., ..., 12866., 16315., 14316.], shape=(4356,))

In [9]:
data["ProductName"].describe()

count                                 431708
unique                                  3606
top       Cream Hanging Heart T-Light Holder
freq                                    1801
Name: ProductName, dtype: object

In [10]:
data.describe()

,TransactionNo,ProductNo,Price,Quantity,CustomerNo
count,424892.000000,4.317080e+05,431708.000000,431708.000000,431664.000000
mean,564631.026082,1.114346e+05,12.372838,10.164185,15227.421814
std,10561.827284,2.748072e+05,7.468426,179.479710,1703.283574
min,545220.000000,1.000200e+04,5.130000,-80995.000000,12004.000000
25%,555648.750000,2.206400e+04,10.680000,1.000000,13842.000000
50%,565401.000000,2.269900e+04,11.940000,4.000000,15137.000000
75%,573931.000000,2.329800e+04,14.090000,12.000000,16717.000000
max,581587.000000,1.000849e+06,660.620000,80995.000000,18287.000000

In [11]:
data["Quantity"]

0         12.0
1         36.0
2         12.0
3         12.0
4          6.0
          ...
431703     1.0
431704     2.0
431705     2.0
431706     2.0
431707     2.0
Name: Quantity, Length: 431708, dtype: float64

In [12]:
data["Price"]

0         21.47
1         10.65
2         11.53
3         10.65
4         11.94
          ...
431703    17.90
431704    14.48
431705    14.48
431706    14.48
431707    14.48
Name: Price, Length: 431708, dtype: float64

In [13]:
data["Country"]

0         United Kingdom
1         United Kingdom
2         United Kingdom
3         United Kingdom
4         United Kingdom
               ...
431703    United Kingdom
431704    United Kingdom
431705    United Kingdom
431706    United Kingdom
431707    United Kingdom
Name: Country, Length: 431708, dtype: str

In [15]:
df=pd.read_csv('sales_transaction.csv')

In [16]:
df

,TransactionNo,Date,ProductNo,ProductName,Price,Quantity,CustomerNo,Country
0,581482,12/9/2019,22485,Set Of 2 Wooden Market Crates,21.47,12.0,17490.0,United Kingdom
1,581475,12/9/2019,22596,Christmas Star Wish List Chalkboard,10.65,36.0,13069.0,United Kingdom
2,581475,12/9/2019,23235,Storage Tin Vintage Leaf,11.53,12.0,13069.0,United Kingdom
3,581475,12/9/2019,23272,Tree T-Light Holder Willie Winkie,10.65,12.0,13069.0,United Kingdom
4,581475,12/9/2019,23239,Set Of 4 Knick Knack Tins Poppies,11.94,6.0,13069.0,United Kingdom
...,...,...,...,...,...,...,...,...
431704,545333,3/1/2019,22745,Poppy's Playhouse Bedroom,14.48,2.0,17333.0,United Kingdom
431705,545333,3/1/2019,22746,Poppy's Playhouse Livingroom,14.48,2.0,17333.0,United Kingdom
431706,545333,3/1/2019,22747,Poppy's Playhouse Bathroom,14.48,2.0,17333.0,United Kingdom
431707,545333,3/1/2019,22748,Poppy's Playhouse Kitchen,14.48,2.0,17333.0,United Kingdom
431708,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [18]:
df.shape #row ... , columns

(431709, 8)

In [19]:
df.dtypes # what type is each right now ?

TransactionNo        str
Date                 str
ProductNo            str
ProductName          str
Price            float64
Quantity         float64
CustomerNo       float64
Country              str
dtype: object

In [20]:
df.head()

,TransactionNo,Date,ProductNo,ProductName,Price,Quantity,CustomerNo,Country
0,581482,12/9/2019,22485,Set Of 2 Wooden Market Crates,21.47,12.0,17490.0,United Kingdom
1,581475,12/9/2019,22596,Christmas Star Wish List Chalkboard,10.65,36.0,13069.0,United Kingdom
2,581475,12/9/2019,23235,Storage Tin Vintage Leaf,11.53,12.0,13069.0,United Kingdom
3,581475,12/9/2019,23272,Tree T-Light Holder Willie Winkie,10.65,12.0,13069.0,United Kingdom
4,581475,12/9/2019,23239,Set Of 4 Knick Knack Tins Poppies,11.94,6.0,13069.0,United Kingdom

In [21]:
df.tail()

,TransactionNo,Date,ProductNo,ProductName,Price,Quantity,CustomerNo,Country
431704,545333,3/1/2019,22745,Poppy's Playhouse Bedroom,14.48,2.0,17333.0,United Kingdom
431705,545333,3/1/2019,22746,Poppy's Playhouse Livingroom,14.48,2.0,17333.0,United Kingdom
431706,545333,3/1/2019,22747,Poppy's Playhouse Bathroom,14.48,2.0,17333.0,United Kingdom
431707,545333,3/1/2019,22748,Poppy's Playhouse Kitchen,14.48,2.0,17333.0,United Kingdom
431708,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [24]:
df.isnull().sum()

TransactionNo     0
Date              1
ProductNo         1
ProductName       1
Price             1
Quantity          1
CustomerNo       45
Country           1
dtype: int64

In [25]:
# Rows with no TransactionNo or no Price can't be analyzed at all
df = df.dropna(subset=['TransactionNo', 'Price'])

# Rows with a blank ProductName are junk
df = df[df['ProductName'].notna() & (df['ProductName'].str.strip() != '')]

In [26]:
# Rows with no TransactionNo or no Price can't be analyzed at all
df = df.dropna(subset=['TransactionNo', 'Price'])

# Rows with a blank ProductName are junk
df = df[df['ProductName'].notna() & (df['ProductName'].str.strip() != '')]

In [27]:
df['Date'] = pd.to_datetime(df['Date'], format='%m/%d/%Y', errors='coerce')
df = df.dropna(subset=['Date'])  # drop any dates that failed to parse

In [28]:
df = df[df['Price'] > 0]
df = df[df['Quantity'] != 0]

In [29]:
df['TransactionNo'] = df['TransactionNo'].str.replace('^C', '', regex=True)
df['ProductName'] = df['ProductName'].str.strip()
df['Country'] = df['Country'].str.strip()

In [30]:
df['Revenue'] = df['Quantity'] * df['Price']

In [32]:
print(df.shape)
print(data['ReturnFlag'].value_counts())
print(df.isnull().sum())
df.head()

(431708, 9)
ReturnFlag
False    424892
True       6816
Name: count, dtype: int64
TransactionNo     0
Date              0
ProductNo         0
ProductName       0
Price             0
Quantity          0
CustomerNo       44
Country           0
Revenue           0
dtype: int64

,TransactionNo,Date,ProductNo,ProductName,Price,Quantity,CustomerNo,Country,Revenue
0,581482,2019-12-09,22485,Set Of 2 Wooden Market Crates,21.47,12.0,17490.0,United Kingdom,257.64
1,581475,2019-12-09,22596,Christmas Star Wish List Chalkboard,10.65,36.0,13069.0,United Kingdom,383.40
2,581475,2019-12-09,23235,Storage Tin Vintage Leaf,11.53,12.0,13069.0,United Kingdom,138.36
3,581475,2019-12-09,23272,Tree T-Light Holder Willie Winkie,10.65,12.0,13069.0,United Kingdom,127.80
4,581475,2019-12-09,23239,Set Of 4 Knick Knack Tins Poppies,11.94,6.0,13069.0,United Kingdom,71.64

In [33]:
df = df.sort_values('Date').reset_index(drop=True)
df.to_csv('cleaned_sales_data.csv', index=False)

In [34]:
df_new=df.dropna()

In [35]:
df_new

,TransactionNo,Date,ProductNo,ProductName,Price,Quantity,CustomerNo,Country,Revenue
0,545333,2019-03-01,22748,Poppy's Playhouse Kitchen,14.48,2.0,17333.0,United Kingdom,28.96
1,545232,2019-03-01,22611,Vintage Union Jack Shopping Bag,7.66,3.0,15676.0,United Kingdom,22.98
2,545232,2019-03-01,22384,Lunch Bag Pink Polkadot,5.97,10.0,15676.0,United Kingdom,59.70
3,545232,2019-03-01,71459,Hanging Jam Jar T-Light Holders,11.12,24.0,15676.0,United Kingdom,266.88
4,545232,2019-03-01,22045,Spaceboy Gift Wrap,10.68,25.0,15676.0,United Kingdom,267.00
...,...,...,...,...,...,...,...,...,...
431703,581498,2019-12-09,22041,"Record Frame 7"" Single Size",6.19,2.0,14498.0,United Kingdom,12.38
431704,581498,2019-12-09,22059,Ceramic Strawberry Design Mug,6.19,1.0,14498.0,United Kingdom,6.19
431705,581498,2019-12-09,22069,Brown Pirate Treasure Chest,6.19,3.0,14498.0,United Kingdom,18.57
431706,581498,2019-12-09,21934,Skull Shoulder Bag,6.19,1.0,14498.0,United Kingdom,6.19
431707,581482,2019-12-09,22485,Set Of 2 Wooden Market Crates,21.47,12.0,17490.0,United Kingdom,257.64